// <auto-generated />
using System;
using GamesProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesProject.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    partial class GameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("GamesProject.Entities.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GenreID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GamesProject.Entities.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Action"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            ID = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Simulation"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Strategy"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Puzzle"
                        },
                        new
                        {
                            ID = 8,
                            Name = "IDle"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Casual"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Horror"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Survival"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Shooter"
                        },
                        new
                        {
                            ID = 13,
                            Name = "MMO"
                        },
                        new
                        {
                            ID = 14,
                            Name = "Racing"
                        },
                        new
                        {
                            ID = 15,
                            Name = "Fighting"
                        },
                        new
                        {
                            ID = 16,
                            Name = "Music"
                        },
                        new
                        {
                            ID = 17,
                            Name = "Educational"
                        },
                        new
                        {
                            ID = 18,
                            Name = "Card"
                        },
                        new
                        {
                            ID = 19,
                            Name = "Board"
                        },
                        new
                        {
                            ID = 20,
                            Name = "Arcade"
                        },
                        new
                        {
                            ID = 21,
                            Name = "Platformer"
                        },
                        new
                        {
                            ID = 22,
                            Name = "Roguelike"
                        },
                        new
                        {
                            ID = 23,
                            Name = "Metroidvania"
                        },
                        new
                        {
                            ID = 24,
                            Name = "PvP"
                        },
                        new
                        {
                            ID = 25,
                            Name = "PvE"
                        },
                        new
                        {
                            ID = 26,
                            Name = "Co-op"
                        },
                        new
                        {
                            ID = 27,
                            Name = "Singleplayer"
                        },
                        new
                        {
                            ID = 28,
                            Name = "Multiplayer"
                        },
                        new
                        {
                            ID = 29,
                            Name = "Local Multiplayer"
                        },
                        new
                        {
                            ID = 30,
                            Name = "Online Multiplayer"
                        },
                        new
                        {
                            ID = 31,
                            Name = "Cross-platform Multiplayer"
                        });
                });

            modelBuilder.Entity("GamesProject.Entities.Game", b =>
                {
                    b.HasOne("GamesProject.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
